### PR TITLE
Add my homepage design proposal - #1

### PR DESCRIPTION
**Pull request by Notiooo**

### CODE REVIEW

**Comment by JuliaBoczkowska** [comment]
Purrfect design, we can merge ฅ^•ﻌ•^ฅ

**Review by JuliaBoczkowska — APPROVED** [review]
Purrfect design proposal, we can merge ฅ^•ﻌ•^ฅ

**Review by michalzielinski913 — APPROVED** [review]
Looks good

**Review by bartryc570 — APPROVED** [review]
Great design!

**Pull request merged**
